version: 2

jobs:
  build:
    working_directory: /data_logger
    docker:
      - image: inflowsys/elixir-container:1.7.3-otp21

    steps:
      - type: checkout
      - type: cache-restore
        key: inflownet-{{ arch }}-{{ .Branch }}-{{ checksum "/data_logger/mix.lock" }}
      - type: shell
        command: mix local.hex --force
      - type: shell
        command: mix hex.organization auth inflowmatix --key $HEX_KEY
      - type: shell
        command: MIX_ENV=test mix deps.get
      - type: shell
        command: mix local.rebar --force
      - type: shell
        command: MIX_ENV=test mix compile
      - type: shell
        command: mix format --check-formatted
      - type: shell
        command: MIX_ENV=test mix test
      - type: cache-save
        key: inflownet-{{ arch }}-{{ .Branch }}-{{ checksum "/data_logger/mix.lock" }}
        paths:
          - /data_logger/deps
          - /data_logger/_build
