name: Test Data Logger and publish
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      working-directory: ./data_logger
    steps:
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.12.3'
        otp-version: '24.1.5'
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Hex and Dependencies
      run: |
        mix local.hex --force
        mix local.rebar --force
        mix hex.organization auth inflowmatix --key ${{ secrets.HEX_KEY }}
        mix deps.get
      working-directory: /home/runner/work/data_logger/data_logger
    - name: Test
      run: |
        MIX_ENV=test mix deps.compile
        MIX_ENV=test mix compile
        MIX_ENV=test mix format --check-formatted
        MIX_ENV=test mix test
      working-directory: /home/runner/work/data_logger/data_logger
